services:
  nginx:
    image: miks:nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miks_nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - api
      - web
    networks:
      - miks_net
      - dokploy-network
    labels:
      - "traefik.docker.network=dokploy-network"
    restart: unless-stopped