worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
	worker_connections 1024;
	use epoll;
	multi_accept on;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
					'$status $body_bytes_sent "$http_referer" '
					'rt=$request_time uct="$upstream_connect_time" '
					'urt="$upstream_response_time" uht="$upstream_header_time" ';
	
	#logs
	access_log /var/log/nginx/access.log main;

	# Performance optimizations
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;

	# Security headers
	add_header X-Frame-Options "SAMEORIGIN" always;
	add_header X-Content-Type-Options "nosniff" always;
	add_header X-XSS-Protection "1; mode=block" always;
	add_header Referrer-Policy "strict-origin-when-cross-origin" always;

	# Gzip compression
	gzip on;
	gzip_vary on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

	# Rate limiting
	limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

	# HTTP server
	server {
		listen 80;
		http2 on;
		server_name localhost;

		# CSP header
		add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-src 'none ';" always;

		# Proxy settings
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header Connection "upgrade";
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_read_timeout 86400;
		proxy_send_timeout 86400;

		# Proxy pass to Next.js server
		location / {
			proxy_pass http://web:3000;
			proxy_cache_bypass $http_upgrade;
		}

		# Api pass to Nest.js server
		location /api/ {
			limit_req zone=api_limit burst=20 nodelay;
			proxy_pass http://api:3000;
		}

		# Deny access to hidden files
		location ~ /\. {
			deny all;
			log_not_found off;
			access_log off;
		}
	}
}