/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as AuthedWorkspaceIdRouteImport } from './routes/_authed/workspace.$id'
import { Route as AuthAuthVerifyEmailRouteImport } from './routes/_auth/auth.verify-email'
import { Route as AuthAuthResetPasswordRouteImport } from './routes/_auth/auth.reset-password'
import { Route as AuthAuthRegisterRouteImport } from './routes/_auth/auth.register'
import { Route as AuthAuthLoginRouteImport } from './routes/_auth/auth.login'
import { Route as AuthAuthForgotPasswordRouteImport } from './routes/_auth/auth.forgot-password'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/_auth/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkspaceIdRoute = AuthedWorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthAuthVerifyEmailRoute = AuthAuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthResetPasswordRoute = AuthAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthRegisterRoute = AuthAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthForgotPasswordRoute = AuthAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/workspace/$id': typeof AuthedWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/workspace/$id': typeof AuthedWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_auth/auth': typeof AuthAuthRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_auth/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/_auth/auth/login': typeof AuthAuthLoginRoute
  '/_auth/auth/register': typeof AuthAuthRegisterRoute
  '/_auth/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/_auth/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/_authed/workspace/$id': typeof AuthedWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/workspace/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_auth/auth'
    | '/_authed/dashboard'
    | '/_auth/auth/forgot-password'
    | '/_auth/auth/login'
    | '/_auth/auth/register'
    | '/_auth/auth/reset-password'
    | '/_auth/auth/verify-email'
    | '/_authed/workspace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthAuthRoute: typeof AuthAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workspace/$id': {
      id: '/_authed/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof AuthedWorkspaceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_auth/auth/verify-email': {
      id: '/_auth/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthAuthVerifyEmailRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    '/_auth/auth/reset-password': {
      id: '/_auth/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthAuthResetPasswordRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    '/_auth/auth/register': {
      id: '/_auth/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    '/_auth/auth/forgot-password': {
      id: '/_auth/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthForgotPasswordRouteImport
      parentRoute: typeof AuthAuthRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedWorkspaceIdRoute: typeof AuthedWorkspaceIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedWorkspaceIdRoute: AuthedWorkspaceIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthAuthRouteChildren {
  AuthAuthForgotPasswordRoute: typeof AuthAuthForgotPasswordRoute
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
  AuthAuthResetPasswordRoute: typeof AuthAuthResetPasswordRoute
  AuthAuthVerifyEmailRoute: typeof AuthAuthVerifyEmailRoute
}

const AuthAuthRouteChildren: AuthAuthRouteChildren = {
  AuthAuthForgotPasswordRoute: AuthAuthForgotPasswordRoute,
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
  AuthAuthResetPasswordRoute: AuthAuthResetPasswordRoute,
  AuthAuthVerifyEmailRoute: AuthAuthVerifyEmailRoute,
}

const AuthAuthRouteWithChildren = AuthAuthRoute._addFileChildren(
  AuthAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthAuthRoute: AuthAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
